#!/bin/sh
#
# $Id: dhcp3-server.init.d,v 1.4 2003/07/13 19:12:41 mdz Exp $
#

# On what interfaces should the DHCP server (dhcpd) serve DHCP requests?
#       Separate multiple interfaces with spaces, e.g. "eth0 eth1".
INTERFACES="r_veth"
SERVER="10.254.236.2"
# Additional options that are passed to the DHCP server daemon?
OPTIONS=""

NAME="dhcrelay"
DAEMON="/usr/sbin/${NAME}"
CFG_FILE="/etc/default/${NAME}"

# Read configuration variable file if it is present
[ -r "${CFG_FILE}" ] && . "${CFG_FILE}"

# Sanity checks
test -f /usr/sbin/dhcrelay || exit 0

echo INTERFACES=$INTERFACES
echo OPTIONS=$OPTIONS

case "$1" in
        start)
                printf "Starting DHCP relay: "
                test -d /var/lib/dhcp/ || mkdir -p /var/lib/dhcp/
                start-stop-daemon -S -q -x ${DAEMON} -- -q -a $OPTIONS -i $INTERFACES $SERVER
                [ $? = 0 ] && echo "OK" || echo "FAIL"
                ;;
        stop)
                printf "Stopping DHCP server: "
                start-stop-daemon -K -q -x ${DAEMON}
                [ $? = 0 ] && echo "OK" || echo "FAIL"
                ;;
        restart | force-reload)
                $0 stop
                $0 start
                if [ "$?" != "0" ]; then
                        exit 1
                fi
                ;;
        *)
                echo "Usage: $0 {start|stop|restart|force-reload}"
                exit 1
esac

exit 0
